# Site Settings
name: Ирина Иванова
email: irina.ivanova@protonmail.com
description: >-
  Личный блог Ирины Ивановой обо всём, что её интересует: винил, дети, инвестиции, книгопечатание, может быть ещё куда-нибудь занесёт.
baseurl: "https://irina-ivanova.eu"
url: https://irina-ivanova.eu
permalink: /:year/:month/:day/:title
github_username: iriiiina

# Build Settings
markdown: kramdown

# Other
safe: true
timezone: "Europe/Tallinn"
encoding: utf-8

# Plugins
plugins:
  - jekyll-paginate

# Pagination Settings
paginate: 10
