# Site Settings
name: Ирина Иванова
email: irina.ivanova@protonmail.com
description: >-
  Персональный блог Ирины Ивановой
baseurl: ""
#url: https://irina-ivanova.eu
url: https://iriiiina.github.io/personal-page
permalink: /:year/:month/:day/:title
github_username: iriiiina

# Build Settings
markdown: kramdown

# Other
safe: true
timezone: "Europe/Tallinn"
encoding: utf-8

# Plugins
plugins:
  - jekyll-paginate

# Pagination Settings
paginate: 10
