# Site settings
name: Cognitio Liber | Книго-ориентированный блог
email: irina.ivanova@protonmail.com
description: >-
  Блог про книгу, как физический объект
baseurl: ""
url: https://book.irina-ivanova.eu
permalink: /:year/:month/:day/:title
github_username: iriiiina

# Build settings
markdown: kramdown
sass:
  sass_dir: css
  style: compressed
  sourcemap: none

# Minify HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

# Other
safe: true
timezone: "Europe/Tallinn"
encoding: utf-8