name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Yaml-Checker
    - uses: leon-th/yaml-checker@v1.0.0

